### ISSUE TITLE
maven central repository

### ISSUE THREAD

**Issue by scizeron** [gregwhitaker/catnap#9]
Hi, 
Thanks for your great job. I would be very interested about that you have done, could it be possible that you publish and make your artifacts available in maven central repository.

**Comment by gregwhitaker** [comment]
I can look into publishing them to maven central as well.  They are currently published in JCenter as it is a lot less red tape to get them there.

**Comment by scizeron** [comment]
OK it sounds good in JCenter, thanks for your reply.
